name: Makefile CI

on:
  push:
    branches: [ "vext_k6789v1_64-user-12-SP1A.210812.016-37379-release-keys" ]
  pull_request:
    branches: [ "vext_k6789v1_64-user-12-SP1A.210812.016-37379-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
